# Generated by Django 6.0.6 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectactivity_projectlabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectactivity',
            name='action',
            field=models.CharField(
                choices=[
                    ('project_created', 'Project created'),
                    ('project_updated', 'Project updated'),
                    ('member_added', 'Member added'),
                    ('member_removed', 'Member removed'),
                    ('member_role_changed', 'Member role changed'),
                    ('task_created', 'Task created'),
                    ('task_assigned', 'Task assigned'),
                    ('task_status_changed', 'Task status changed'),
                    ('task_updated', 'Task updated'),
                    ('task_deleted', 'Task deleted'),
                    ('comment_added', 'Comment added'),
                    ('attachment_added', 'Attachment added'),
                    ('attachment_deleted', 'Attachment deleted'),
                    ('checklist_updated', 'Checklist updated'),
                ],
                max_length=40,
            ),
        ),
    ]
