# Generated by Django 6.0.6 on 2026-07-15 10:13

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.validators.avatar_upload_path, validators=[accounts.validators.validate_avatar]),
        ),
    ]
