# Generated by Django 6.0.6 on 2026-07-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project_invitation', 'Project invitation'), ('member_added', 'Member added'), ('task_assigned', 'Task assigned'), ('task_updated', 'Task updated'), ('task_status_changed', 'Task status changed'), ('new_comment', 'New comment'), ('attachment_added', 'Attachment added'), ('checklist_updated', 'Checklist updated'), ('due_soon', 'Task due soon'), ('task_overdue', 'Task overdue'), ('member_role_changed', 'Member role changed')], max_length=40),
        ),
    ]
